name: adi
version: '0.0.1'
main: re.mxc.adi.Adi
api-version: '1.20'
authors: [ Stuart ]
commands:
  adi:
    description: Main commande
    usage: /adi <reload>
    aliases: [advanceddiscordintegration]
    permission: adi.command.admin